name: CI with Cache

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: cache-917a624

      - name: prime-cache-917a624
        run: |
          if [ -d ~/.npm ]; then
            echo "Cache hit!"
          else
            echo "Cache miss!"
          fi
